import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href="/Mint" > 
          <a>
            <h2>Mint &rarr;</h2>
            <p>Mint page</p>
            </a>
          </Link>
          <Link href="/Result" > 
          <a>
            <h2>Result &rarr;</h2>
            <p>Result page</p>
            </a>
          </Link>

      </div>
  )
}
